/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ovt_util_CGMC */

#ifndef _Included_ovt_util_CGMC
#define _Included_ovt_util_CGMC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ovt_util_CGMC
 * Method:    newFiles
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ovt_util_CGMC_newFiles
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
