/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ovt_mag_Trace */

#ifndef _Included_ovt_mag_Trace
#define _Included_ovt_mag_Trace
#ifdef __cplusplus
extern "C" {
#endif
#undef ovt_mag_Trace_EPS
#define ovt_mag_Trace_EPS 0.0010D
#undef ovt_mag_Trace_HMIN
#define ovt_mag_Trace_HMIN 0.0010D
#undef ovt_mag_Trace_FF
#define ovt_mag_Trace_FF 1.01D
#undef ovt_mag_Trace_MAXCOUNT
#define ovt_mag_Trace_MAXCOUNT 300L
#undef ovt_mag_Trace_STMIN
#define ovt_mag_Trace_STMIN 0.01D
#undef ovt_mag_Trace_STEPMAX
#define ovt_mag_Trace_STEPMAX 1.0D
#undef ovt_mag_Trace_MXX
#define ovt_mag_Trace_MXX 200L
#undef ovt_mag_Trace_NMAX
#define ovt_mag_Trace_NMAX 3L
#undef ovt_mag_Trace_IMAX
#define ovt_mag_Trace_IMAX 11L
#undef ovt_mag_Trace_NUSE
#define ovt_mag_Trace_NUSE 7L
#undef ovt_mag_Trace_STEPMIN
#define ovt_mag_Trace_STEPMIN 0.0020D
#undef ovt_mag_Trace_RMAX
#define ovt_mag_Trace_RMAX 100.0D
#undef ovt_mag_Trace_KPINDEX
#define ovt_mag_Trace_KPINDEX 0L
#undef ovt_mag_Trace_DSTINDEX
#define ovt_mag_Trace_DSTINDEX 0L
#undef ovt_mag_Trace_SINT
#define ovt_mag_Trace_SINT 1L
#undef ovt_mag_Trace_IMF_Y
#define ovt_mag_Trace_IMF_Y 1L
#undef ovt_mag_Trace_COST
#define ovt_mag_Trace_COST 2L
#undef ovt_mag_Trace_TILT
#define ovt_mag_Trace_TILT 2L
#undef ovt_mag_Trace_SWP
#define ovt_mag_Trace_SWP 3L
#undef ovt_mag_Trace_IMF_Z
#define ovt_mag_Trace_IMF_Z 4L
/*
 * Class:     ovt_mag_Trace
 * Method:    mdirectoryJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ovt_mag_Trace_mdirectoryJNI
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ovt_mag_Trace
 * Method:    lastlineJNI
 * Signature: (D[D[DDDIDIIDI[D)V
 */
JNIEXPORT void JNICALL Java_ovt_mag_Trace_lastlineJNI
  (JNIEnv *, jclass, jdouble, jdoubleArray, jdoubleArray, jdouble, jdouble, jint, jdouble, jint, jint, jdouble, jint, jdoubleArray);

/*
 * Class:     ovt_mag_Trace
 * Method:    tracelineJNI
 * Signature: (D[DDDIDI[D[D[D[D[D[D[DIIDI[I[D)V
 */
JNIEXPORT void JNICALL Java_ovt_mag_Trace_tracelineJNI
  (JNIEnv *, jclass, jdouble, jdoubleArray, jdouble, jdouble, jint, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdouble, jint, jintArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
