/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ovt_mag_model_Tsyganenko2001 */

#ifndef _Included_ovt_mag_model_Tsyganenko2001
#define _Included_ovt_mag_model_Tsyganenko2001
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ovt_mag_model_Tsyganenko2001
 * Method:    tsyganenko2001JNI
 * Signature: ([DDDDDDDD[D)V
 */
JNIEXPORT void JNICALL Java_ovt_mag_model_Tsyganenko2001_tsyganenko2001JNI
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
