/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ovt_mag_model_Tsyganenko87 */

#ifndef _Included_ovt_mag_model_Tsyganenko87
#define _Included_ovt_mag_model_Tsyganenko87
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ovt_mag_model_Tsyganenko87
 * Method:    tsyganenko87JNI
 * Signature: ([DDDD[D)V
 */
JNIEXPORT void JNICALL Java_ovt_mag_model_Tsyganenko87_tsyganenko87JNI
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
