/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ovt_mag_model_Tsyganenko89 */

#ifndef _Included_ovt_mag_model_Tsyganenko89
#define _Included_ovt_mag_model_Tsyganenko89
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ovt_mag_model_Tsyganenko89
 * Method:    tsyganenko89JNI
 * Signature: ([DDDD[D)V
 */
JNIEXPORT void JNICALL Java_ovt_mag_model_Tsyganenko89_tsyganenko89JNI
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
