/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ovt_util_Utils */

#ifndef _Included_ovt_util_Utils
#define _Included_ovt_util_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ovt_util_Utils
 * Method:    earthJNI
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ovt_util_Utils_earthJNI
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ovt_util_Utils
 * Method:    sun_vectJNI
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ovt_util_Utils_sun_1vectJNI
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
