/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ovt_mag_model_Tsyganenko96 */

#ifndef _Included_ovt_mag_model_Tsyganenko96
#define _Included_ovt_mag_model_Tsyganenko96
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ovt_mag_model_Tsyganenko96
 * Method:    tsyganenko96JNI
 * Signature: ([DDDD[D)V
 */
JNIEXPORT void JNICALL Java_ovt_mag_model_Tsyganenko96_tsyganenko96JNI
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
