/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ovt_object_TLESat */

#ifndef _Included_ovt_object_TLESat
#define _Included_ovt_object_TLESat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ovt_object_TLESat
 * Method:    getSatPosJNI
 * Signature: (Ljava/lang/String;[D[[D[[DI)I
 */
JNIEXPORT jint JNICALL Java_ovt_object_TLESat_getSatPosJNI
  (JNIEnv *, jobject, jstring, jdoubleArray, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
